export const JobType = {
  STRIPE_JOBS: 'STRIPE_JOBS',
  CREATE_STRIPE_WEBHOOK_JOB: 'CREATE_STRIPE_WEBHOOK_JOB',
  CREATE_STRIPE_EVENT_FETCHING_DATA_JOB:
    'CREATE_STRIPE_EVENT_FETCHING_DATA_JOB',
  CREATE_STRIPE_EVENT_HISTORY_JOB: 'CREATE_STRIPE_EVENT_HISTORY_JOB',

  USED_SERVICES_JOBS: 'USED_SERVICES_JOBS',
  CREATE_USED_SERVICES_JOB: 'CREATE_USED_SERVICES_JOB',
};
